### ISSUE TITLE
How can I use ES6 in vue.config.js?

### ISSUE THREAD

**Issue by mahammad-sixberries** [cheap-glitch/vue-cli-plugin-sitemap#13]
```
import routes from "./src/router/routes";
       ^^^^^^

SyntaxError: Unexpected identifier
```
also require does not work as routes are dependent on store

```
const routes = require("./src/router/routes");

import store from "@/store";
       ^^^^^

SyntaxError: Unexpected identifier
```
and on and on ...

**Comment by cheap-glitch** [comment]
Could you clarify why you'd want to use ES6 import statements in the first place? `vue.config.js` is only going to be read by Node anyway.

**Comment by bastiW** [comment]
It is easier to read the syntax within
// src/routes.js
is really deviating from what I am used to.

Usually I have something like this, it makes use of autocompletion in my IDE:

```
import Home from "./pages/Home";
import About from "./pages/About";


export default new Router({
  mode: "history",
  base: process.env.BASE_URL,
  linkExactActiveClass: "active",
  routes: [

    {
      path: "/",
      name: "home",
      component: Home
    },
    {
      path: "/about",
      name: "about",
      component: About
    }
  ]
});
```
yours is something like that:

```
module.exports = [
	{
		path: '/',
		name: 'home',
		component: () => import(/* webpackChunkName: "home" */ './Home')
	},
	{
		path: '/about',
		name: 'about',
		component: () => import(/* webpackChunkName: "about" */ './About')
	},
]
```

**Comment by arogonov** [comment]
> Could you clarify why you'd want to use ES6 import statements in the first place? `vue.config.js` is only going to be read by Node anyway.

Let's say I have many paths in Router. I am using modules.

In vue.config.js
`const routes = require('./src/router/routes');`

In ./src/router/routes.js
```
import foo from '@/router/modules/foo';
import bar from '@/router/modules/bar';
import baz from '@/router/modules/baz';

const routes = [
  {
    path: '/:lang(jp|es|fr)?',
    children: [
      ...foo,
      ...bar,
      ...baz,
    ]
  {
];
```

I get the expected error
```
Error loading vue.config.js:
ERROR  SyntaxError: Cannot use import statement outside a module
```

**Comment by cheap-glitch** [comment]
> I get the expected error
> ```
> Error loading vue.config.js:
> ERROR  SyntaxError: Cannot use import statement outside a module
> ```

You can circumvent this by using https://github.com/standard-things/esm. There are a few caveat though:
1. You can't import `.vue` files in your `routes.js` module because `esm` won't know how to load them (since they're processed by webpack via `vue-loader` and we can't do that here). So you'll have to rely on dynamic requires (e.g. `component: () => import(/* webpackChunkName: "about" */ '../views/About.vue'`), which will gleefully be ignored by the plugin.
2. You can't use the `@` placeholder in the import paths as this is a bit of sugar syntax offered by `vue-loader` to clean up the paths. Simply write a relative path as if including a CommonJS module.

I'll update the readme tomorrow with a detailed example of this setup.
