### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by alexsonnay** [cheap-glitch/vue-cli-plugin-sitemap#7]
Not working at all for me.

Did everything that is written in your doc but I do get this error 

 ERROR  Error loading vue.config.js:
 ERROR  SyntaxError: Cannot use import statement outside a module
/src/router/index.js:1
import Vue from "vue";
^^^^^^

**Comment by cheap-glitch** [comment]
That's because the code imported with `require()` will be executed by Node, and it doesn't expect `import` statements. The simplest solution is a setup similar as [the one in the readme](https://github.com/cheap-glitch/vue-cli-plugin-sitemap#use-with-vue-router) with a script that doesn't import anything and only exports a simple array of routes using the CommonJS `module.exports` syntax.

That way, both `vue.config.js` and the main script (or any intermediary script, e.g. `router.js`) can import it -- the first one using `require()` and the second one `import` (since webpack can resolve both ES6 and CommonJS modules).

I don't claim it's the best solution, it's true that it's a bit clunky but it's the only one I found that allows importing the routes in both files.
